name: Release
on:
    push:
        tags:
            - "v*"

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: golangci/golangci-lint-action@v2
              with:
                  version: v1.40
            - run: curl -sL https://taskfile.dev/install.sh | sh
            - run: curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
            - name: Test
              run: ./bin/task test
              env:
                  PATH: $PATH:./bin
                  CGO_ENABLED: 0
            - name: Build
              run: ./bin/task build
              env:
                  CGO_ENABLED: 0
            - name: Release
              run: ./bin/goreleaser
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
